{% set name = "hydromt_sfincs" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hydromt_sfincs-{{ version }}.tar.gz
  sha256: d7b3148875e04f31a625bb72e4b36bc0ad31a6bc66194ec15f081d41fe6f4118

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - flit
    - python {{ python_min }}
  run:
    - affine
    - geopandas >=1.0
    - hydromt >=0.10.1,<1.0
    - numba
    - numpy
    - pandas
    - pillow
    - pyflwdir >=0.5.10
    - pyproj
    - python >={{ python_min }}
    - rasterio
    - scipy
    - shapely
    - xarray
    - xugrid >=0.12,<1.0

test:
  imports:
    - hydromt_sfincs
  commands:
    - pip check
    - hydromt --models
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/hydromt_sfincs/
  summary: HydroMT plugin for SFINCS models.
  doc_url: https://deltares.github.io/hydromt_sfincs/stable
  dev_url: https://github.com/Deltares/hydromt_sfincs
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deltares-service-account
    - DirkEilander
    - Leynse
    - roeldegoede
