{% set name = "hydromt_sfincs" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydromt_sfincs-{{ version }}.tar.gz
  sha256: 8c9312e8734d29799586535b895587be74ee405b6841427ee33da948fe916aaf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - flit
    - python >=3.8
  run:
    - affine
    - geopandas >=0.8
    - hydromt >=0.8,<0.9
    - numba
    - numpy
    - pandas
    - pillow
    - pyflwdir >=0.5.5
    - pyproj
    - python >=3.8
    - rasterio
    - scipy
    - shapely
    - xarray

test:
  imports:
    - hydromt_sfincs
  commands:
    - pip check
    - hydromt --models
  requires:
    - pip

about:
  home: https://pypi.org/project/hydromt_sfincs/
  summary: HydroMT plugin for SFINCS models.
  doc_url: https://deltares.github.io/hydromt_sfincs/stable
  dev_url: https://github.com/Deltares/hydromt_sfincs
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DirkEilander
    - Leynse
    - roeldegoede
